image: microsoft/dotnet:2.1-sdk

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - chmod +x ./scripts/build.sh
    - ./scripts/build.sh

test:
  stage: test
  script:
    - chmod +x ./scripts/test.sh
    - ./scripts/test.sh

deploy:
  stage: deploy
  only:
    - master
  script:
    - chmod +x ./scripts/deploy.sh
    - ./scripts.deploy.sh $MYGET_API_KEY
